### ISSUE TITLE
using rename() yields link error

### ISSUE THREAD

**Issue by SuperIlu** [tkchia/build-ia16#15]
The following short test program yields a link error:
#include <stdio.h>

int main(int argc, char *argv[]) {
  rename("foo.txt", "bar.txt");

  return 0;
}

-->
![image](https://user-images.githubusercontent.com/1155988/80912950-071db700-8d41-11ea-8ddc-abaad9375145.png)

**Comment by tkchia** [comment]
Hello @SuperIlu,

Apologies for the bug!  It turns out that `rename (, )` in the Newlib library was set to be implemented in terms of the `_link` and `_unlink` syscalls, which is correct for Unix, but wrong for MS-DOS.

I have corrected the bug in the `newlib-ia16` sources.  I will try to update the binary packages in the next few days or so.

Thank you!

**Comment by tkchia** [comment]
Hello @SuperIlu,

> > I will try to update the binary packages in the next few days or so.

I have meanwhile added an updated FreeDOS package to the [release page](https://github.com/tkchia/build-ia16/releases/tag/20200321).  If it does not work for you, please let me know.

Thank you!
