### ISSUE TITLE
tinyasm repo does not seem to exist

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/build-ia16#17]
In https://github.com/tkchia/build-ia16/blob/master/fetch.sh#L54 we try to load from github.com/tkchia/tinyasm.git

This does not seem to exist. Running `./fetch.sh` in a new empty build-ia16 directory results in:

```
*** Successfully downloaded ubasic-ia16 ***
*** Trying to download tinyasm Git repository using SSH ***
Cloning into 'tinyasm'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
*** SSH failed; falling back on using HTTPS to download tinyasm ***
Cloning into 'tinyasm'...
Username for 'https://github.com': 
```

**Comment by ecm-pushbx** [comment]
Entering any login for the prompt results in:

```
remote: Repository not found.
fatal: repository 'https://github.com/tkchia/tinyasm.git/' not found
*** Could not download tinyasm! ***
```

**Comment by tkchia** [comment]
Hello @ecm-pushbx ,

Oops, sorry for the mistake --- and thanks for the report.  I recently removed my fork of `tinyasm`.

Since `tinyasm` is a sort of "extra" package and not really part of the toolchain, I have modified `fetch.sh` to no longer download it.  `./build.sh extra` will still download it (on demand) from [upstream](https://github.com/nanochess/tinyasm), though.

Thank you!
