### ISSUE TITLE
how pass more of 255 characters of arguments to gcc in dosbox?

### ISSUE THREAD

**Issue by ingcparga** [tkchia/build-ia16#19]
Thank you for your support. The issue is simple, actually i need pass several arguments to gcc when build the .bin files, but DosBox limit the arguments to 255 characters. This is a problem because everyday i add more and more arguments necessary to adecuate build executable and i cant dispense with other arguments.
The concret ask is: Is possible pass more arguments via some script or macro like linker or something in such a way that it is not necessary to pass arguments through the command line? The bat file is not a solution because use command line.
Thanks for all.
P.D. As offtopic feedback, i solved the problem about programing eeprom and volatile data the segments cs,ss,es. The solution was as you recommended, modifying to align and generating labels with information about the .data section in the ld script, finally a code at the beginning of the binary executable in asm to copy the .data section to the designated segments. In short, it is possible to generate executable files for use in an 8088 like embeded system. Thank you again.

**Comment by tkchia** [comment]
Hello @ingcparga,

> In short, it is possible to generate executable files for use in an 8088 like embeded system. Thank you again.

Thank you.  Glad to be of help!

> The concret ask is: Is possible pass more arguments via some script or macro like linker or something in such a way that it is not necessary to pass arguments through the command line?

You can use GCC's `@`_file_ [feature](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html) to get it to read options from a separate file and "insert" them into the command line.  For example, if you have a `bar.lnk` file which says
```
foo.c
-o foo.bin
```
then
```
i16gcc @bar.lnk
```
will basically do the same thing as
```
i16gcc foo.c -o foo.bin
```

This is useful because the file in `@`_file_ can be longer than MS-DOS's 126-character command line limit.

You can either manually write the contents of the _file_, or you can dynamically build it up at build time using batch file commands, makefile recipe commnds, etc.

Thank you!

**Comment by ingcparga** [comment]
Thank you for your answer. Exactly is it was i looking for. 
I have another offtopic question. You have planned to implement in a future the mcmodel compact and large?

**Comment by tkchia** [comment]
Hello @ingcparga,

> Thank you for your answer. Exactly is it was i looking for.

No problem --- glad to be of help again. :-)

> I have another offtopic question. You have planned to implement in a future the mcmodel compact and large?

Yes, I hope to implement these some day, but I have not really found the way to do so.

(In the meantime, if you need to write programs that use the compact, large, or huge memory models, you will probably have to use a compiler that already support them --- e.g. Open Watcom, or Borland Turbo C++.  But note that these compiler's copyright licenses are different from GCC's.)

Thank you!
